### ISSUE TITLE
color in v w x y z in Bold Condensed

### ISSUE THREAD

**Issue by impallari** [impallari/Cabin#7]
In bold condensed: v w y are lighter, x is bolder @kalapi 
![screen shot 2016-11-04 at 2 53 50](https://cloud.githubusercontent.com/assets/3036973/19996071/b548fa64-a23b-11e6-9f24-e27b7969ec8a.png)

**Comment by kalapi** [comment]
Hello @impallari 

I fixed this and have opened a PR on Marc's repo. I guess we need to figure out a strategy for pushing fixes (i.e. should I push to your upstream or Marc's). At the moment since Marc is in charge of pushing updates, i'm happy for him to check and merge.

<img width="326" alt="screen shot 2016-11-06 at 1 06 36 pm" src="https://cloud.githubusercontent.com/assets/15804460/20036142/3941b8ca-a425-11e6-8c66-e2e829c132e9.png">

Cheers,
Kalapi
